### ISSUE TITLE
MPVClient.pas contains MPVBasePlayer.pas code

### ISSUE THREAD

**Issue by BazzaCuda** [nbuyer/LibMPVDelphi#1]
HI,

I'm really interested in studying your MPV code and getting your demo project2 running.

However, it seems like at some point the code for MPVClient has been overwritten by the contents of MPVBasePlayer.
Delphi complained that the unit name didn't match the file name (MPVClient.pas says "unit MPVBasePlayer") and I noticed that both files, contain a definition of TMPVBasePlayer. 

Would you be able to take a look please and rectify the repository?

Thanks.
Baz.

**Comment by BazzaCuda** [comment]
If it's any help to you, the latest good version of MPVClient.pas was in the d04b56f commit, labelled "Update FMX.MPVPlayer.pas" on March 9, 2023. I downloaded that version and the project compiles!

It went wrong with the d10f48a commit, labelled "Update MPVClient.pas", also March 9, 2023.

cheers,
Baz.

**Comment by nbuyer** [comment]
Fixed. Sorry about that.
