### ISSUE TITLE
Hint. Feature for FMX

### ISSUE THREAD

**Issue by HemulGM** [nbuyer/LibMPVDelphi#4]
For FMX, it is necessary not to create a window and embed it in a form, but to receive frame data from the library and then draw it somewhere else.

**Comment by nbuyer** [comment]
Thank you for your suggestion, technically you are right, the main problems are as follows.

1. I'm not very familiar with FMX compared to VCL, and I'm not very happy with FMX.

2. The simplest way to interface to MPV is mpv_set_property("wid"), wid is actually a window handle, of course there might be other ways to do this but I haven't looked too closely.

3. TMPVPlayerControl actually duplicates the logic of TMediaPlayerControl, an internal player component, with a slightly different implementation. I don't think it's a big deal to do this.

Of course, it would be easier (but not run faster I guess) to do what you said, but I personally don't have that much free time or ability to look into it. :)
